(function(){
"use strict";
if(!window.CloudOdyssey||!window.CloudOdysseyBackend){console.error("Backend Forge dependencies missing");return;}
var CO=window.CloudOdyssey,B=window.CloudOdysseyBackend,KEY="cloud_odyssey_backend_forge_v1";
var st=Object.assign({project:0,checks:{},grades:{}},JSON.parse(localStorage.getItem(KEY)||"{}"));
var $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from((r||document).querySelectorAll(s));
var save=()=>localStorage.setItem(KEY,JSON.stringify(st));
var esc=s=>String(s||"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
var stages=[
 ["Invariant + SLO","State the business invariant, latency/freshness objective and unacceptable failure mode."],
 ["API contract","Version request/response schemas, errors, compatibility and pagination/streaming semantics."],
 ["Identity boundary","Define authenticated principal, tenant boundary, roles/scopes and secret ownership."],
 ["Persistence model","Choose authoritative state, indexes, transaction boundary and retention policy."],
 ["Concurrency + idempotency","Make retries, duplicates and concurrent writers converge deterministically."],
 ["Async + delivery","Design queue/outbox/webhook semantics, retries, leases, DLQ and poison-event handling."],
 ["Observability","Add request/trace IDs, structured logs, metrics, traces and business reconciliation."],
 ["Security + abuse","Threat-model authorization, injection, replay, exfiltration, abuse and rate-limit behavior."],
 ["Performance + cost","Measure p95/p99, database work, cache hit rate, queue age and unit economics."],
 ["Fault injection + tests","Prove network timeout, duplicate, partial commit, stale cache and dependency failure behavior."],
 ["Runbook + rollback","Define evidence preservation, blast-radius controls, known-good rollback and resume criteria."],
 ["Staff-level defense","Explain WHY this design, rejected alternatives, ownership, residual risk and migration path."]
];
function P(id,title,icon,scenario,stack,flow,why,alt,required,files){return {id,title,icon,scenario,stack,flow,why,alt,required,files};}
var projects=[
 P("contract","API Contract & Compatibility Gateway","⇄","Design a public learning API that can evolve for years without silently breaking old clients.",["OpenAPI","HTTP","Schema Versioning","Contract Tests"],["Client","Gateway","Validator","Service","Response"],"Explicit contracts, error semantics and compatibility policy reduce accidental coupling between clients and backend releases.","A collection of undocumented JSON handlers is faster at first but makes breaking changes and client debugging expensive.",["version","contract","compatibility","idempotency","error","evidence"],[["openapi.yaml","Machine-readable public contract."],["api/_lib/contracts.js","Server validation boundary."],["tests/contract.test.js","Compatibility tests."],["docs/versioning.md","Evolution/deprecation policy."]]),
 P("identity","Identity, RBAC & Tenant Isolation","⛨","Turn anonymous-device mode into a secure multi-tenant SaaS where no caller can choose another tenant ID.",["OIDC/Auth","RBAC","Tenant Membership","Policy Tests"],["Identity Provider","Session","Policy","Tenant Data"],"Tenant identity must be derived from an authenticated principal; trusting a tenant ID supplied by the browser is not an authorization boundary.","Client-side role checks improve UX but cannot protect server data.",["authentication","authorization","tenant","least privilege","deny","audit"],[["auth/session.js","Session verification."],["auth/policy.js","Authorization rules."],["db/migrations/tenant.sql","Membership schema."],["tests/authz_negative.test.js","Cross-tenant denial tests."]]),
 P("idempotency","Idempotent Command Processing","↻","A mobile client retries a purchase/progress command five times after a timeout. Produce one business effect.",["Idempotency-Key","Postgres UNIQUE","Transactions","Receipts"],["Client","Command API","Idempotency Record","Transaction","Result"],"A stable idempotency key lets the server distinguish a retry from a new command and return the original result.","Trying to detect duplicates after side effects occur is race-prone and can double-charge or double-write.",["idempotency","unique","transaction","retry","converge","receipt"],[["api/commands.js","Command handler."],["db/idempotency.sql","Unique key/receipt table."],["tests/retry.test.js","Concurrent/retry tests."],["runbook.md","Duplicate-effect recovery."]]),
 P("event-ledger","Event Ledger + Projections","≋","Preserve every meaningful learning action while still serving fast current proficiency.",["Event Log","Projection","Snapshots","Replay"],["Command","Event Ledger","Projector","Snapshot","Read API"],"Immutable facts preserve history; projections make current reads efficient and rebuildable.","One mutable progress JSON is easy to write but destroys lineage and complicates correction/replay.",["event","append-only","projection","snapshot","replay","version"],[["events/schema.json","Event envelope."],["projector.js","Projection logic."],["db/events.sql","Ledger tables/indexes."],["tests/replay.test.js","Projection rebuild test."]]),
 P("outbox","Transactional Outbox + Webhooks","⇢","A database commit succeeds but the email/webhook provider times out. Deliver exactly the intended downstream notification eventually.",["Transactional Outbox","Webhook Signatures","Retry","DLQ"],["Transaction","Outbox","Publisher","Webhook","Consumer"],"Writing business state and outbox intent in one transaction prevents the dual-write gap; delivery can retry independently.","Calling a webhook inside the business transaction couples database success to an unreliable network dependency.",["outbox","transaction","retry","signature","dead letter","idempotency"],[["db/outbox.sql","Outbox schema."],["worker/publish.js","Outbox publisher."],["webhooks/sign.js","HMAC signatures."],["tests/delivery.test.js","Timeout/replay tests."]]),
 P("queue","Durable Job Queue + Worker Leasing","⚙","Run long grading/export jobs across many workers without two workers processing the same job indefinitely.",["Postgres Queue","SKIP LOCKED","Lease","Backoff"],["Producer","Jobs Table","Lease","Worker","Result"],"Leases and atomic claims provide bounded ownership; expired leases allow recovery from crashed workers.","A boolean processing flag can strand work forever after a worker dies.",["lease","skip locked","retry","backoff","heartbeat","poison"],[["db/jobs.sql","Durable queue schema."],["worker/claim.js","Atomic leasing."],["worker/run.js","Retry/backoff."],["tests/worker_crash.test.js","Lease-expiry recovery."]]),
 P("rate-limit","Rate Limiting & Abuse Control","⌁","Protect expensive grading and AI endpoints from bursts, scraping and abusive automation while preserving legitimate traffic.",["Token Bucket","Distributed Store","Bot Signals","Quotas"],["Request","Identity/IP Key","Limiter","Service"],"Distributed limits bound resource consumption consistently across serverless instances and can reflect plan entitlements.","In-memory counters are cheap but unreliable across horizontally scaled function instances.",["rate limit","distributed","quota","429","burst","entitlement"],[["middleware/rateLimit.js","Limiter."],["policies/quotas.js","Plan-specific quotas."],["tests/burst.test.js","Burst/fairness tests."],["runbook.md","Abuse escalation."]]),
 P("cache","Cache Coherence & Stampede Protection","◫","A popular readiness dashboard expires for thousands of users at once. Keep latency low without melting Postgres.",["Cache","TTL","Singleflight","Invalidation"],["Request","Cache","Singleflight","DB","Refresh"],"Singleflight/request coalescing prevents many identical cache misses from becoming a database stampede.","A TTL alone reduces steady-state reads but does not protect the instant a hot key expires.",["cache","stampede","singleflight","ttl","invalidation","stale"],[["cache/readiness.js","Cache-aside policy."],["cache/locks.js","Refresh coalescing."],["tests/stampede.test.js","Concurrent expiry test."],["metrics/cache.md","Hit/miss/refresh SLO."]]),
 P("realtime","Real-Time Progress Delivery","⌁","Update dashboards across tabs/devices as assessments finish without polling every second.",["SSE","WebSocket","Pub/Sub","Backpressure"],["Event","Broker","Realtime Gateway","Client"],"Push delivery reduces polling waste, but requires reconnect, ordering, authorization and backpressure semantics.","Aggressive polling is simpler but multiplies read load and adds latency between state changes and UI updates.",["reconnect","ordering","backpressure","authorization","cursor","heartbeat"],[["realtime/server.js","SSE/WebSocket gateway."],["realtime/protocol.md","Cursor/order contract."],["tests/reconnect.test.js","Resume tests."],["runbook.md","Broker/gateway degradation."]]),
 P("billing","Billing & Entitlement Ledger","$","Convert subscriptions into trustworthy feature access without letting duplicate provider webhooks grant/revoke access incorrectly.",["Billing Webhooks","Entitlements","Ledger","Idempotency"],["Payment Provider","Webhook","Event Ledger","Entitlement Projection","API"],"Provider events should be authenticated, deduplicated and projected into internal entitlements rather than queried ad hoc on every request.","Trusting a client-side plan flag or processing every webhook as new creates security and billing errors.",["signature","webhook","idempotency","entitlement","ledger","reconcile"],[["webhooks/billing.js","Verified provider webhook."],["db/entitlements.sql","Internal entitlement projection."],["tests/webhook_replay.test.js","Replay/order tests."],["jobs/reconcile_billing.js","Provider reconciliation."]]),
 P("observe","Observability & SLO Control Plane","◎","Detect a backend that returns HTTP 200 while grading is stale, queues are aging and writes are silently failing.",["OpenTelemetry","Structured Logs","SLO","Reconciliation"],["Request","Trace","Metrics/Logs","SLO","Alert/Runbook"],"Technical telemetry plus business reconciliation detects both infrastructure failure and logically incorrect success.","CPU and HTTP error rate alone can remain green while the product is producing wrong outcomes.",["trace","request id","slo","reconcile","p99","alert"],[["observability/otel.js","Trace instrumentation."],["observability/slo.md","SLI/SLO definitions."],["dashboards/backend.json","Operational dashboard."],["tests/alert_path.md","Alert-to-runbook test."]]),
 P("dr","Multi-Region Recovery & Chaos","⛨","Lose a region or critical dependency and resume service without corrupting verified attempts or duplicating external effects.",["Backups","Failover","RPO/RTO","Chaos","Reconciliation"],["Primary","Durable Evidence","Failover","Reconcile","Resume"],"Recovery is only complete when business invariants are proven after failover, not when servers simply respond again.","Active-active everything can reduce some failover latency but increases consistency complexity and cost.",["rpo","rto","failover","reconcile","rollback","evidence"],[["infra/dr.tf","Recovery topology."],["tests/chaos.md","Failure experiments."],["recovery/reconcile.js","Business validation."],["runbook.md","Failover/resume sequence."]])
];
function p(){return projects[st.project%projects.length];}
function key(i){return p().id+"-"+i;}
function done(){return stages.filter((_,i)=>st.checks[key(i)]).length;}
function gradeVal(){return Number(st.grades[p().id]||0);}
function render(){
 var root=$("#view-backend-forge");if(!root)return;var pr=p(),completion=Math.round(done()/stages.length*100),grade=gradeVal(),overall=Math.round(completion*.55+grade*.45);
 root.innerHTML='<div class="view-heading"><div><span class="micro">STAFF / PRINCIPAL BACKEND ENGINEERING</span><h2>Backend Systems Forge</h2><p>Build the failure semantics behind serious SaaS and platform systems. Every project forces correctness, concurrency, security, observability, recovery and tradeoff reasoning.</p></div><span class="enterprise-badge">12 PROJECTS • 144 CHECKPOINTS</span></div>'+
 '<div class="backend-forge-shell"><aside class="bf-side glass"><div class="bf-head"><span class="micro">SYSTEM CAMPAIGN</span><h3>Distributed backend patterns</h3><p>Completion is local evidence. Architecture defense is graded by the real server-side assessment API.</p></div><div class="bf-projects">'+projects.map((x,i)=>{var n=stages.filter((_,s)=>st.checks[x.id+"-"+s]).length;return '<button class="bf-project '+(i===st.project?'active ':'')+(n===12?'complete':'')+'" data-bf-project="'+i+'"><span class="ico">'+x.icon+'</span><div><b>'+esc(x.title)+'</b><span>'+esc(x.stack.slice(0,3).join(" • "))+'</span></div><em>'+n+'/12</em></button>';}).join("")+'</div></aside>'+
 '<section class="bf-main glass"><div class="bf-title"><span class="micro">PROJECT '+String(st.project+1).padStart(2,"0")+'</span><h2>'+pr.icon+' '+esc(pr.title)+'</h2><p>'+esc(pr.scenario)+'</p><div class="bf-chips">'+pr.stack.map(x=>'<span class="bf-chip">'+esc(x)+'</span>').join("")+'</div></div>'+
 '<div class="bf-why"><div class="bf-proof"><b>WHY THIS PATTERN</b><p>'+esc(pr.why)+'</p></div><div class="bf-proof"><b>WHY NOT THE SHORTCUT</b><p>'+esc(pr.alt)+'</p></div></div>'+
 '<div class="bf-flow">'+pr.flow.map((x,i)=>'<div class="bf-node"><b>'+esc(x)+'</b><span>'+(i===0?'entry':i===pr.flow.length-1?'business result':'failure boundary')+'</span></div>'+(i<pr.flow.length-1?'<div class="bf-arrow">→</div>':'')).join("")+'</div>'+
 '<div class="bf-checks">'+stages.map((x,i)=>'<label class="bf-check"><input type="checkbox" data-bf-check="'+i+'" '+(st.checks[key(i)]?'checked':'')+'><div><b>'+String(i+1).padStart(2,"0")+'. '+x[0]+'</b><p>'+x[1]+'</p></div><em>+'+Math.round(55/12)+'%</em></label>').join("")+'</div></section>'+
 '<aside class="bf-review glass"><div class="bf-score"><span class="micro">PROJECT EVIDENCE</span><strong>'+overall+'%</strong><span>'+done()+'/12 architecture checkpoints • server defense '+grade+'%</span></div><div class="bf-files"><span class="micro">EXPECTED REPOSITORY ARTIFACTS</span>'+pr.files.map(x=>'<div class="bf-file"><code>'+esc(x[0])+'</code><span>'+esc(x[1])+'</span></div>').join("")+'</div>'+
 '<div class="bf-review-box"><span class="micro">DEFEND THE ARCHITECTURE</span><textarea id="bfAnswer" placeholder="Explain WHO/WHAT/WHERE/WHEN/WHY, failure boundary, rejected alternative, evidence, and rollback..."></textarea><button id="bfGrade">Grade architecture defense on real server</button><button id="bfSmoke" style="background:rgba(255,255,255,.025)">Run live backend smoke proof</button><div id="bfResult" class="bf-result">No server grade yet.</div></div></aside></div>';
 $$("[data-bf-project]").forEach(b=>b.onclick=()=>{st.project=+b.dataset.bfProject;save();render();});
 $$("[data-bf-check]").forEach(b=>b.onchange=()=>{st.checks[key(+b.dataset.bfCheck)]=b.checked;save();render();});
 $("#bfGrade").onclick=async()=>{var t=$("#bfAnswer").value.trim();if(!t){CO.toast("Defend the design first");return;}$("#bfResult").textContent="Calling server grader...";try{var r=await B.grade(t,pr.required,{type:"backend-forge:"+pr.id,blind:true,duration_ms:90000});st.grades[pr.id]=r.score;save();$("#bfResult").textContent="SERVER GRADE "+r.score+"%\nrequest "+(r.request_id||"—")+"\nverification "+r.verification+"\n"+JSON.stringify(r.dimensions,null,2);}catch(e){$("#bfResult").textContent=(e.data?JSON.stringify(e.data,null,2):e.message);}};
 $("#bfSmoke").onclick=async()=>{try{var r=await B.request("smoke");$("#bfResult").textContent="LIVE BACKEND SMOKE\n"+JSON.stringify(r.checks,null,2);}catch(e){$("#bfResult").textContent=e.message;}};
}
function install(){
 var nav=$("#nav"),work=$("#workspace");if(!nav||!work)return;
 var b=document.createElement("button");b.className="nav-item";b.dataset.view="backend-forge";b.innerHTML="<span>⚙</span><b>Backend Systems Forge</b><em>23</em>";b.onclick=()=>{CO.setView("backend-forge");$("#pageTitle").textContent="Backend Systems Forge";render();};nav.appendChild(b);
 var sec=document.createElement("section");sec.className="view";sec.id="view-backend-forge";work.appendChild(sec);render();
}
window.CloudOdysseyBackendForge={projects:projects,getState:()=>st};
install();
})();