
(function(){
"use strict";
if(!window.CloudOdyssey){console.error("Speaking Lab requires CloudOdyssey");return;}
var CO=window.CloudOdyssey, KEY="cloud_odyssey_speaking_v1";
var st=Object.assign({mode:"vocab",vocabMode:"definition",category:"all",index:0,selected:null,answered:false,correct:0,attempts:0,termStats:{},starIndex:0,starAnswers:{},starScores:{},rapidStarted:null},JSON.parse(localStorage.getItem(KEY)||"{}"));
var $=function(s,r){return (r||document).querySelector(s);};
var $$=function(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s));};
var save=function(){localStorage.setItem(KEY,JSON.stringify(st));};
var esc=function(s){return String(s||"").replace(/[&<>"]/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c];});};
var shuffle=function(a){var x=a.slice();for(var i=x.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),t=x[i];x[i]=x[j];x[j]=t;}return x;};

function V(term,cat,def,why,vs,natural,keys){return {term:term,cat:cat,def:def,why:why,vs:vs,natural:natural,keys:keys||term.toLowerCase().split(/\s+/)};}
var vocab=[
V("Grain","Modeling","The exact business meaning represented by one row.","It prevents two teams from aggregating different facts under the same table name.","Schema: schema describes fields; grain describes what one row means.","The first thing I clarified was the grain: one row per reservation night.",["row","business","meaning"]),
V("Business key","Modeling","The stable business attributes that uniquely identify a fact or entity.","Retries and corrections need a stable identity independent of execution IDs.","Surrogate key: surrogate keys are technical identifiers; business keys carry domain identity.","I used reservation_id plus stay_date as the business key for deterministic reconciliation.",["stable","identify","business"]),
V("Surrogate key","Modeling","A generated technical identifier used instead of a natural business key.","It simplifies joins and dimension management without redefining business identity.","Business key: business key comes from the domain; surrogate key is system-generated.","The warehouse uses a surrogate customer key, but matching still starts from the business identity.",["generated","technical","identifier"]),
V("Fact table","Modeling","A table of measurable events at a declared grain.","It centralizes business measurements and connects them to conformed dimensions.","Dimension: facts contain measurable events; dimensions provide descriptive context.","The reservation-night fact is the source for occupancy and revenue measures.",["measure","event","grain"]),
V("Conformed dimension","Modeling","A shared dimension with consistent meaning across multiple fact tables.","It stops department-specific definitions from fragmenting analytics.","Local dimension: a local dimension serves one mart; a conformed dimension is reused consistently.","We used a conformed resort dimension so sales and occupancy reports slice the same way.",["shared","consistent","dimension"]),
V("SCD Type 1","Modeling","Dimension handling that overwrites old values with current truth.","It is simple when historical attribute values do not matter.","SCD2: Type 1 loses history; Type 2 preserves effective history.","We used Type 1 for a corrected spelling because historical spellings had no analytical value.",["overwrite","current","history"]),
V("SCD Type 2","Modeling","Dimension handling that preserves historical versions with effective intervals.","It lets historical reports reproduce what was true at that time.","SCD1: Type 1 overwrites; Type 2 versions.","Guest tier was SCD2 because historical stays must retain the tier that was effective then.",["history","effective","version"]),
V("Semantic layer","Modeling","A governed business-facing layer that standardizes metrics and dimensions.","It keeps KPI logic from being rewritten in every dashboard.","Raw layer: raw preserves source; semantic exposes certified business meaning.","I exposed only the certified semantic layer to BI so metric logic stayed consistent.",["governed","metric","business"]),
V("Source of truth","Architecture","The system or certified state designated as authoritative for a fact.","Without one, conflicting systems can each appear valid.","System of record: often similar; source of truth emphasizes the trusted consumption state.","Snowflake current-state plus its certified release pointer was the source of truth after recovery.",["authoritative","trusted","state"]),
V("Data contract","Architecture","A versioned agreement for schema, meaning, quality, and behavioral expectations.","It makes producer changes reviewable before consumers silently break.","Schema: schema is structural; a contract also includes semantics and operational expectations.","We versioned the reservation contract so producers could evolve without silent downstream loss.",["versioned","agreement","producer"]),
V("Lineage","Architecture","Traceable relationships from source data through transformations to outputs.","It lets teams explain where a value came from and what a change can affect.","Logging: logs record events; lineage records data dependency and derivation.","I traced the KPI from source event through silver, gold, and the certified view.",["source","transform","output"]),
V("Authoritative state","Architecture","The state a system is allowed to treat as current business truth.","It separates observed/transient states from business-approved current state.","Latest state: latest timestamp is not necessarily authoritative business precedence.","The latest arrival was not authoritative; decision sequence determined authoritative state.",["current","business","truth"]),
V("Failure boundary","Architecture","The point where a component can succeed while another dependent effect can still fail.","It tells you which evidence is required before claiming end-to-end success.","Transaction boundary: transaction boundaries are atomic scopes; failure boundaries can exist between them.","The API timeout sat outside the Snowflake transaction boundary, so I treated it as a separate failure boundary.",["failure","component","boundary"]),
V("Blast radius","Reliability","The scope of users, data, services, or business processes affected by a failure.","Bounding it prevents an incident response from making the problem larger.","Root cause: root cause explains why; blast radius explains how far impact spread.","Before changing production I bounded the blast radius to 17 resorts and three downstream marts.",["scope","impact","affected"]),
V("SLO","Reliability","A measurable reliability target for a service or data product.","It converts reliability from a vague goal into an operating threshold.","SLA: an SLO is an internal target; an SLA is a contractual commitment.","Our freshness SLO required inventory data to be under five minutes old.",["target","reliability","service"]),
V("SLA","Reliability","A formal service commitment, often with contractual consequences.","It defines externally promised service performance.","SLO: SLO guides operations; SLA formalizes the commitment.","The customer-facing SLA was looser than the internal SLO so we had an operating buffer.",["contract","commitment","service"]),
V("Error budget","Reliability","The tolerated amount of unreliability implied by an SLO.","It helps teams balance feature delivery with reliability work.","Availability target: the target defines the goal; the error budget defines how much failure is tolerable.","The burn rate told us we were consuming the monthly error budget too quickly.",["slo","failure","tolerated"]),
V("MTTR","Reliability","Mean time to restore or recover service after failure.","It measures operational recovery effectiveness.","MTBF: MTTR is recovery speed; MTBF is time between failures.","The new runbook reduced our target MTTR by making evidence and rollback steps explicit.",["recover","time","incident"]),
V("Runbook","Reliability","A documented operational procedure for detection, triage, recovery, validation, and escalation.","It makes incident response repeatable instead of person-dependent.","Playbook: terms overlap; runbook usually emphasizes executable operational steps.","The runbook tells on-call exactly how to preserve evidence before restarting the stream.",["procedure","recovery","steps"]),
V("Observability","Reliability","The ability to infer internal system state from metrics, logs, traces, and correlated evidence.","It lets teams diagnose unknown failures, not just known thresholds.","Monitoring: monitoring checks expected conditions; observability supports investigation of unexpected behavior.","We added lineage-aware observability so a freshness alert could be traced to the exact failed microbatch.",["metrics","logs","traces"]),
V("Idempotency","Streaming","The property that repeating the same logical operation produces no additional business effect.","Retries are inevitable; idempotency keeps retries from duplicating state.","Deduplication: dedupe removes duplicates; idempotency defines repeat-safe operation behavior.","The destination command was idempotent because every retry reused the same business operation ID.",["repeat","same","effect"]),
V("Exactly-once business effect","Streaming","A business outcome applied once even if transport or processing retries occur.","It focuses on end-state correctness rather than marketing claims about transport semantics.","Exactly-once processing: processing semantics alone do not guarantee external business effects.","We achieved an exactly-once business effect with stable identity, outcome lookup, reconciliation, and certified publication.",["business","once","retry"]),
V("At-least-once delivery","Streaming","A delivery model where records may be delivered more than once but should not be lost.","It requires downstream idempotency or deduplication.","At-most-once: at-most-once may lose records; at-least-once may duplicate them.","Kafka could redeliver, so the sink was designed for at-least-once delivery with idempotent state changes.",["duplicate","delivery","not lost"]),
V("Replay","Streaming","Another delivery or reprocessing of previously seen logical content.","Safe replay enables recovery without double-counting.","Retry: retry repeats an operation after failure; replay often reprocesses historical input.","I treated the second E200 delivery as replay, so it contributed zero additional points.",["again","logical","content"]),
V("Late data","Streaming","Data that arrives after its expected event-time window or operational deadline.","Production logic must decide whether late records still change authoritative state.","Out-of-order data: out-of-order is sequence disorder; late data specifically misses a time expectation.","The 73-hour correction was late but still valid under the 96-hour correction contract.",["arrives","after","event"]),
V("Event time","Streaming","The time an event occurred in the business/source domain.","It supports correct time-window semantics despite transport delays.","Processing time: event time is source/business time; processing time is when compute sees the event.","We windowed customer activity by event time because processing delays should not move the business event.",["event","occurred","source"]),
V("Processing time","Streaming","The time the processing engine handles an event.","It is useful operationally but can distort business timing when events arrive late.","Event time: processing time reflects compute arrival, not when the business event happened.","Processing time helped measure pipeline latency, but event time drove business windows.",["processor","handles","time"]),
V("Watermark","Streaming","An estimate of event-time progress used to close time-based operations.","It bounds state for windowing but does not establish business finality.","Checkpoint: watermark is time-progress logic; checkpoint is fault-recovery state.","The watermark closed provisional windows, but late corrections still reached the durable ledger.",["event-time","progress","window"]),
V("Checkpoint","Streaming","A coordinated snapshot of processing state for fault recovery.","It restores a dataflow consistently after failure.","Savepoint: checkpoint is runtime recovery; savepoint is an explicit operator-managed snapshot for planned changes.","The checkpoint restored Flink state, but I still reconciled external Snowflake effects separately.",["state","fault","recovery"]),
V("Savepoint","Streaming","An explicit durable snapshot used for planned upgrades, rescaling, or controlled migration.","It gives operators a deliberate restore point tied to stable operator state.","Checkpoint: savepoints are operator-controlled and portable; checkpoints are runtime recovery artifacts.","I used stop-with-savepoint before rescaling so operator state mapping was explicit.",["planned","snapshot","restore"]),
V("Fencing","Streaming","Preventing obsolete workers, producers, or owners from continuing to mutate state.","It stops split-brain execution after failover or deployment overlap.","Locking: fencing rejects stale owners even if they still run; a lock alone may be lost or expire ambiguously.","We fenced the old sender epoch before activating the replacement worker.",["obsolete","owner","reject"]),
V("Offset","Streaming","A position within a Kafka partition.","It identifies physical ordering in a partition but not business precedence.","Event ID: offset is transport position; event ID identifies logical content.","I preserved topic ID, partition, and offset as physical capture evidence.",["partition","position","kafka"]),
V("Consumer group","Streaming","A Kafka coordination identity that divides partitions among consumers.","It controls processing ownership and restart position across a consumer fleet.","Producer ID: consumer group coordinates readers, not writers.","The production job kept a stable consumer group so restart did not invent a new consumption identity.",["consumer","partition","group"]),
V("Partition key","Streaming","The key used to route records to a partition.","It affects locality and ordering but must not be mistaken for global business order.","Business key: partition keys route transport; business keys define domain identity.","We routed by complete match key so related events stayed together during normal operation.",["route","partition","key"]),
V("Backpressure","Streaming","A condition where downstream processing cannot keep up with incoming data.","It signals capacity or skew problems and can increase lag.","Consumer lag: lag is accumulated delay; backpressure is flow-control pressure causing or reflecting it.","The latency spike was caused by backpressure after one hot partition overloaded a task.",["downstream","keep up","pressure"]),
V("Consumer lag","Streaming","The distance between produced Kafka offsets and consumer progress.","It measures how far behind a consumer is.","Latency: lag is source-position backlog; latency measures elapsed time.","Consumer lag climbed to 4.8 million offsets during the incident.",["behind","offset","consumer"]),
V("Dead-letter queue","Streaming","A separate destination for messages that cannot be processed successfully.","It prevents bad records from blocking the good path while preserving evidence.","Quarantine: often similar; quarantine is broader data-quality isolation, while DLQ commonly means failed messages.","Malformed events went to the DLQ with reason codes instead of disappearing.",["failed","message","preserve"]),
V("Quarantine","Data Quality","An isolated area for records that fail validation but must remain auditable.","It prevents invalid data from contaminating certified outputs without losing evidence.","Drop: dropping removes evidence; quarantine preserves it.","Invalid schemas were quarantined and excluded from publication with explicit dispositions.",["invalid","isolated","evidence"]),
V("Physical capture","Recovery","The concrete transport occurrence identified by source identity and position.","It distinguishes repeated physical deliveries of the same logical event.","Logical event: physical capture is delivery occurrence; logical event is business/source identity.","I retained both physical captures of E200 but classified the second as a logical replay.",["transport","position","delivery"]),
V("Logical event","Recovery","The stable identity of an event independent of where or how many times it was delivered.","It lets replay at a new offset be recognized as the same logical content.","Physical capture: logical identity survives transport retries and new offsets.","The logical event ID prevented a replayed record from creating another business effect.",["identity","event","delivery"]),
V("Input cut","Recovery","An immutable bounded set of source ranges plus completeness evidence for a run.","It prevents mixed retries, missing partitions, and moving-source recovery.","Snapshot: a snapshot is state at a time; an input cut explicitly binds source ranges and proof.","I froze the input cut before child jobs so nobody could discover a different latest range mid-recovery.",["immutable","range","source"]),
V("Workset","Recovery","The immutable bounded set of affected records/keys plus code, rules, and baseline context.","It pins exactly what one recovery attempt is allowed to change.","Input cut: input cut binds source input; workset binds the broader recovery scope and implementation context.","The workset contained only affected campaign keys and the exact source evidence needed to repair them.",["bounded","affected","keys"]),
V("Logical commit","Recovery","A stable identity for an intended external write including target, input, and exact row-set evidence.","It lets lost acknowledgements be resolved without inventing a new write.","Transaction ID: a database transaction ID may be implementation-specific; logical commit is application-level intent.","After the timeout I resolved the same logical commit instead of resending a different batch.",["write","identity","row"]),
V("Canonicalization","Recovery","Contract-defined normalization before comparing or hashing business content.","It makes semantically equal payloads compare equal despite formatting differences.","Serialization: serialization encodes bytes; canonicalization defines one normalized semantic representation.","I canonicalized participant order and timestamps before computing the business hash.",["normalize","hash","compare"]),
V("Content hash","Recovery","A digest representing exact or normalized content.","It provides compact evidence for equality, completeness, and tamper detection.","Row count: row count can match while contents differ; hashes add content evidence.","The row-set hash let us prove the recovered batch matched the original manifest.",["digest","content","hash"]),
V("Version conflict","Recovery","Different business content claiming the same business key and version.","It represents contradictory evidence and should block arbitrary selection.","Replay: replay has same logical content; conflict has divergent content at the same identity/version.","M500 was a version conflict, so I blocked it instead of choosing by arrival time.",["same","version","different"]),
V("Retraction","Recovery","Removal of a previously active complete contribution or effect.","Corrections and voids must remove stale prior state, not only add the new state.","Delete: a delete is a physical/data operation; retraction is the business removal of an earlier contribution.","When the match was voided, I retracted the entire prior participant contribution.",["remove","previous","effect"]),
V("Tombstone","Recovery","A durable marker that a business entity/version is deleted or inactive.","It prevents older versions from reappearing during replay or resync.","Physical delete: tombstones preserve deletion state; physical delete erases a row.","We kept a tombstone so an old reservation version could not be resurrected by replay.",["delete","marker","durable"]),
V("Compare-and-swap","Recovery","An update allowed only when the current value exactly matches an expected predecessor.","It prevents stale publishers from overwriting newer certified state.","Unconditional update: CAS verifies predecessor; unconditional update does not.","The release pointer used compare-and-swap so an old recovery could not reactivate itself.",["expected","predecessor","update"]),
V("Disposition","Recovery","The terminal classification assigned to a captured record, such as accepted, replay, rejected, or conflict.","It proves every input was accounted for exactly once in the recovery logic.","Status flag: disposition is a governed terminal outcome with reasons/evidence, not a casual process status.","Every capture received one terminal disposition before certification.",["terminal","classification","record"]),
V("Certified release","Recovery","An immutable output version that passed all required reconciliation and policy gates.","It separates candidate computation from business-approved publication.","Latest candidate: latest does not imply valid; certified means explicitly proven and activated.","The previous certified release stayed active until every recovery gate passed.",["validated","release","publish"]),
V("Delta Lake","Databricks","A table format providing ACID transactions, schema controls, and versioned data on object storage.","It supports reliable mutable lakehouse state.","Parquet: Parquet is a file format; Delta adds transaction log and table semantics.","Inventory current state lived in Delta so concurrent updates and rollback were controlled.",["acid","table","transaction"]),
V("Delta MERGE","Databricks","An atomic upsert operation that matches source and target rows by condition.","It lets corrections converge deterministically on current state.","Overwrite: overwrite replaces a broader scope; MERGE targets matched business keys.","I used Delta MERGE on inventory_id instead of rewriting the entire table.",["upsert","match","target"]),
V("Change Data Feed","Databricks","Delta functionality exposing row-level changes between table versions.","It supports incremental downstream processing and bounded recovery.","Snapshot: snapshot shows current state; CDF shows how state changed.","I used CDF to reconstruct the exact promotion changes between versions 701 and 706.",["changes","versions","delta"]),
V("Auto Loader","Databricks","Databricks incremental file ingestion optimized for large cloud object stores.","It scales discovery and schema handling without relisting everything.","Batch directory listing: listing is simple but scales poorly for continuous ingestion.","Auto Loader incrementally discovered landing files while preserving checkpointed progress.",["incremental","files","cloud"]),
V("Structured Streaming","Databricks","Spark's incremental stream processing engine using DataFrame APIs and checkpointed state.","It lets batch-like transformations operate continuously with recovery state.","Batch Spark: batch has bounded input; Structured Streaming handles continuously arriving data.","I used Structured Streaming for reservation events because recovery and incremental state were required.",["spark","stream","checkpoint"]),
V("Bronze layer","Databricks","The raw or minimally transformed ingestion layer in a medallion architecture.","It preserves source evidence for replay and audit.","Silver layer: Bronze prioritizes source fidelity; Silver applies validated business structure.","Bronze retained original reservation payloads even when validation failed.",["raw","source","medallion"]),
V("Silver layer","Databricks","The cleaned, validated, deduplicated business-structured layer.","It creates reusable trustworthy records before business aggregates.","Gold layer: Silver standardizes entities/events; Gold serves business products/metrics.","Silver held deduplicated reservation events with schema and quality rules applied.",["clean","validated","medallion"]),
V("Gold layer","Databricks","A business-serving layer containing curated aggregates, marts, or features.","It exposes optimized business outputs after upstream validation.","Silver layer: Gold is consumer/business oriented; Silver is reusable clean data.","The Gold occupancy mart was published only after reconciliation passed.",["business","curated","serve"]),
V("OPTIMIZE","Databricks","A Delta maintenance operation that compacts small files.","It improves scan efficiency after streaming creates fragmented files.","VACUUM: OPTIMIZE reorganizes active files; VACUUM removes old unreferenced files.","We ran OPTIMIZE after fixing the microbatch cadence to reduce the small-file penalty.",["compact","files","delta"]),
V("Z-ORDER","Databricks","A Delta data-layout technique that colocates related column values for data skipping.","It can reduce scanned data for common selective filters.","Partitioning: partitioning creates directory-level groups; Z-ORDER improves locality within data files.","We Z-ORDERed by resort_id because incident queries repeatedly filtered by resort.",["data skipping","columns","layout"]),
V("Unity Catalog","Governance","Databricks governance layer for catalogs, permissions, lineage, and data/AI assets.","It centralizes access policy and discoverability across workspaces.","Workspace ACL: workspace permissions are narrower; Unity Catalog governs data objects across environments.","Unity Catalog enforced which service principal could read Raw versus certified Gold.",["governance","permissions","catalog"]),
V("Expectation","Data Quality","A declared data-quality rule evaluated as data moves through a pipeline.","It turns quality requirements into executable checks and metrics.","Unit test: unit tests validate code logic; expectations validate data properties at runtime.","The DLT expectation rejected null reservation IDs before Gold publication.",["quality","rule","data"]),
V("Freshness","Data Quality","How current a dataset or feature is relative to its expected update time.","A technically correct but stale dataset can still be operationally wrong.","Completeness: completeness asks whether required data exists; freshness asks whether it is recent enough.","The feature values were valid but violated the 15-minute freshness target.",["current","time","data"]),
V("Completeness","Data Quality","Whether all required records, partitions, or fields are present.","It prevents partial data from being mistaken for correct data.","Validity: validity checks allowed values; completeness checks presence/coverage.","We refused certification because one source partition lacked completeness evidence.",["all","required","present"]),
V("Uniqueness","Data Quality","A constraint that a key or entity appears only once at its declared grain.","It detects duplicate business state.","Deduplication: uniqueness is a property/test; deduplication is a method to resolve duplicates.","The uniqueness test on household_id caught a duplicate merge bug.",["one","key","duplicate"]),
V("Referential integrity","Data Quality","The requirement that foreign-key-like references point to valid related entities.","It prevents orphan facts and broken dimensions.","Uniqueness: uniqueness checks duplicate keys; referential integrity checks valid relationships.","We blocked the mart because reservation facts referenced an unknown resort key.",["reference","valid","relationship"]),
V("Reconciliation","Data Quality","Comparison of independently derived expected and actual business states.","It proves downstream state matches the intended source truth.","Validation: validation can check local rules; reconciliation compares states across boundaries.","I reconciled source reservations to the certified occupancy totals before publishing.",["expected","actual","compare"]),
V("dbt test","Analytics","An automated assertion about model data, such as uniqueness, nullability, or relationships.","It makes semantic model assumptions executable in CI and production.","dbt model: the model transforms data; the test proves properties of the result.","A relationship test blocked the mart when a resort dimension key was missing.",["assertion","model","data"]),
V("Incremental model","Analytics","A model that processes only new or changed data instead of rebuilding everything.","It reduces cost and latency when incremental boundaries are trustworthy.","Full refresh: full refresh recomputes all rows; incremental processes bounded changes.","The customer mart used an incremental model keyed by updated_at with a repair path for late changes.",["new","changed","model"]),
V("Exposure","Analytics","A dbt object describing downstream dashboards, apps, or consumers of models.","It connects data lineage to business consumers.","Model: models produce data; exposures describe who consumes it.","The executive occupancy dashboard was registered as an exposure so upstream changes showed consumer impact.",["consumer","dashboard","dbt"]),
V("Feature store","ML","A governed system for reusable feature definitions and serving.","It reduces duplicated feature logic and training-serving skew.","Data warehouse: warehouses store broad data; feature stores add ML-specific definition/freshness/serving semantics.","We registered guest 90-day stay count once and reused it for training and online scoring.",["feature","reuse","serving"]),
V("Point-in-time join","ML","A historical join that only uses feature values available at the label/event time.","It prevents future information leakage into training.","Equality join: equality alone can attach future values.","I used a point-in-time join so cancellation labels never saw features computed after the cancellation.",["feature_time","label_time","leakage"]),
V("Training-serving skew","ML","A difference between how features or preprocessing behave during training and production inference.","It can make strong offline models fail online.","Model drift: skew is implementation/data-path mismatch; drift is distribution/performance change over time.","Parity tests caught a default-value mismatch that caused training-serving skew.",["training","serving","difference"]),
V("Feature freshness","ML","How recently an online/offline feature value was computed relative to its contract.","Stale features can degrade decisions even when serving infrastructure is healthy.","Data freshness: feature freshness is specifically tied to model input semantics and serving needs.","We alerted when propensity features exceeded the 15-minute feature freshness SLO.",["feature","stale","time"]),
V("Experiment tracking","MLOps","Recording parameters, metrics, artifacts, and lineage for model runs.","It makes model results reproducible and comparable.","Logging: logs capture runtime events; experiment tracking captures structured ML run evidence.","MLflow tracked the data version, parameters, RMSE, artifacts, and code SHA for every candidate.",["parameters","metrics","artifacts"]),
V("Model registry","MLOps","A governed catalog of model versions and lifecycle state.","It creates controlled promotion and rollback references.","Experiment tracker: experiments compare runs; registry manages deployable model versions.","The registry held the champion and the exact prior version used for rollback.",["model","version","lifecycle"]),
V("Champion-challenger","MLOps","A pattern comparing the current production model with one or more candidates.","It reduces promotion risk by keeping a proven baseline.","A/B test: A/B tests split live traffic; champion-challenger can include offline/shadow comparison.","The challenger beat the champion overall but failed the Las Vegas weekend slice gate.",["current","candidate","compare"]),
V("Promotion gate","MLOps","A required validation or approval that must pass before a model/release advances.","It prevents recency from becoming the deployment policy.","Metric threshold alone: a full promotion gate can include slices, fairness, lineage, approvals, and rollback readiness.","The candidate could not enter production until every promotion gate passed.",["gate","before","production"]),
V("Data drift","MLOps","A change in input feature distribution relative to a baseline.","It can signal changing populations or upstream data behavior.","Concept drift: data drift changes inputs; concept drift changes the relationship between inputs and target.","We saw data drift in booking lead time but no labeled quality drop yet.",["input","distribution","change"]),
V("Concept drift","MLOps","A change in the relationship between model inputs and the target outcome.","It can degrade model quality even if input distributions appear stable.","Data drift: data drift is input distribution change; concept drift is target relationship change.","The cancellation model showed concept drift after policy changes altered guest behavior.",["relationship","target","change"]),
V("Retraining policy","MLOps","Rules defining when and how a model should be retrained and re-evaluated.","It prevents noisy drift signals from causing uncontrolled model churn.","Scheduled retraining: a policy can be event/quality-driven rather than simply time-based.","Our retraining policy required slice degradation plus sufficient new labels.",["when","retrain","rules"]),
V("RAG","AI","Retrieval-augmented generation: generating answers using retrieved external context.","It improves freshness and grounding for knowledge-intensive AI.","Fine-tuning: RAG supplies external knowledge at query time; fine-tuning changes model behavior/weights.","The concierge used RAG so resort-policy answers came from current approved documents.",["retrieve","generate","context"]),
V("Embedding","AI","A vector representation encoding semantic similarity.","It enables similarity search across text or other objects.","Token ID: tokens are discrete model inputs; embeddings are continuous vector representations.","We embedded approved policy chunks and stored model/version metadata with the index.",["vector","semantic","representation"]),
V("Vector index","AI","A data structure optimized for nearest-neighbor search over embeddings.","It retrieves semantically similar chunks efficiently.","Keyword index: keyword search matches terms; vector search matches semantic proximity.","The vector index retrieved cancellation-policy chunks even when the guest used different wording.",["embedding","search","similar"]),
V("Grounding","AI","Constraining generated output to provided, trusted evidence.","It reduces unsupported claims and improves auditability.","Prompting: prompts guide behavior; grounding anchors factual content to evidence.","The AI answer was grounded in retrieved policy text and required citations.",["evidence","answer","trusted"]),
V("Hallucination","AI","A generated claim that is unsupported, fabricated, or inconsistent with reliable evidence.","It is a key failure mode for factual AI systems.","Uncertainty: uncertainty is lack of confidence; hallucination is unsupported content presented as answer.","We treated uncited policy claims as potential hallucinations and blocked them.",["unsupported","generated","claim"]),
V("Guardrail","AI","A control that constrains model inputs, outputs, tool use, or policy behavior.","It creates boundaries that prompts alone may not reliably enforce.","System prompt: prompts instruct; guardrails add explicit checks/policies outside pure generation.","PII guardrails blocked sensitive guest data from entering the external model call.",["control","policy","model"]),
V("CI/CD","DevOps","Automated integration, testing, and deployment of versioned changes.","It makes releases repeatable and evidence-driven.","Manual deployment: manual steps are harder to review, reproduce, and roll back.","CI blocked the Databricks bundle until unit, integration, and policy checks passed.",["automated","test","deploy"]),
V("Databricks Asset Bundle","DevOps","A versioned deployment specification for Databricks jobs and resources.","It reduces environment drift and supports reproducible releases.","Manual workspace configuration: bundles are code-reviewed and versioned.","The bundle used one source definition with environment-specific catalog variables.",["databricks","deployment","versioned"]),
V("Canary release","DevOps","A release sent to a small controlled subset before wider rollout.","It limits blast radius while collecting real production evidence.","Big-bang release: big-bang exposes everyone immediately.","We canaried the new consumer to five percent before expanding traffic.",["small","release","traffic"]),
V("Rollback","DevOps","Returning production to a known-good prior release or state.","It reduces incident uncertainty when a release regresses.","Forward fix: forward fix changes production again; rollback restores validated prior behavior.","We rolled back to the last known-good model while investigating the failed slice.",["known-good","prior","restore"]),
V("Blue-green deployment","DevOps","Running old and new environments in parallel and switching traffic between them.","It enables fast cutover and rollback.","Canary: blue-green swaps environments; canary gradually exposes traffic.","We used blue-green for the service because traffic could switch back instantly.",["two","environment","switch"]),
V("RBAC","Governance","Role-based access control: permissions assigned through roles rather than individual ad-hoc grants.","It makes access reviewable and scalable.","ABAC: ABAC uses attributes/policies; RBAC primarily uses roles.","RBAC separated ingestion, recovery, publication, and analytics privileges.",["role","permission","access"]),
V("Least privilege","Governance","Granting only the permissions required to perform a task.","It reduces accidental or malicious blast radius.","Admin access: admin is broad; least privilege is intentionally narrow.","The marketing role could query the certified view but not Raw or recovery ledgers.",["minimum","permission","required"]),
V("Tenant isolation","Governance","Preventing one customer's or tenant's data from being visible or mutable by another.","It is fundamental to multi-tenant correctness and security.","Row filtering alone: isolation may require row policies plus service boundaries and tests.","We negative-tested tenant isolation with restricted principals before certification.",["tenant","separate","access"]),
V("Audit trail","Governance","Durable evidence of who changed or accessed what, when, and under which context.","It supports accountability, incident review, and compliance.","Application log: logs may be transient; audit trails are intentionally durable evidence.","The audit trail linked the release approval, query IDs, and restricted-role access tests.",["who","what","when"]),
V("PII","Governance","Personally identifiable information that can identify or relate to a person.","It requires stronger access, movement, and retention controls.","Sensitive data: PII is one category of sensitive data.","We removed guest PII from query tags and restricted Raw payload access.",["person","identify","data"]),
V("Data retention","Governance","Rules controlling how long data/evidence is kept and when it is deleted or archived.","It balances audit/recovery needs with cost and privacy.","Backup policy: backup protects availability; retention governs lifecycle duration.","The incident ledger had a longer retention period than transient runtime logs.",["keep","duration","delete"]),
V("Warehouse credits","FinOps","Snowflake compute consumption units used for warehouse billing.","They make compute cost measurable across recovery/query work.","Bytes scanned: credits measure compute consumption; bytes scanned measure data read.","I reported recovery warehouse credits separately from Kafka and Databricks infrastructure cost.",["snowflake","compute","cost"]),
V("Bytes scanned","FinOps","The amount of data read by a query or workload.","It exposes whether pruning and bounded worksets are effective.","Runtime: runtime can improve by scaling compute even while scan volume remains wasteful.","We reduced bytes scanned by joining from a bounded affected-key table instead of the full history.",["data","read","query"]),
V("Partition pruning","FinOps","Skipping irrelevant partitions based on filters or metadata.","It reduces I/O and cost for bounded queries.","Scaling compute: pruning removes unnecessary work; scaling only executes work faster.","Partition pruning mattered more than adding warehouse size to the recovery query.",["skip","partition","filter"]),
V("Unit cost","FinOps","Cost normalized per business unit such as 1K events, predictions, or recovered keys.","It lets teams compare efficiency as volume changes.","Total cost: total cost grows with volume; unit cost shows efficiency.","We tracked cost per thousand reservation events so scale changes were interpretable.",["cost","per","unit"]),
V("Query profile","FinOps","Execution evidence showing scans, joins, spills, queue time, and operator behavior.","It reveals why a query costs time and compute.","Query text: text shows intent; profile shows actual execution.","The Snowflake query profile proved pruning exceeded 95 percent with zero remote spill.",["execution","scan","spill"]),
V("Spill","FinOps","Intermediate data written outside memory during execution due to pressure.","It can signal skew, insufficient memory, or inefficient joins.","Queue time: spill happens during execution; queue time happens before resources run.","Remote spill identified the large join as the real bottleneck.",["memory","disk","execution"]),
V("Stakeholder","Communication","A person or group affected by or responsible for an outcome.","Engineering communication should translate the same work into that audience's decision language.","User: users consume outcomes; stakeholders may fund, govern, operate, or depend on them.","I changed the explanation for the stakeholder: executives heard value/risk, SRE heard SLO/recovery.",["audience","outcome","decision"]),
V("Tradeoff","Communication","A conscious choice where improving one property costs another.","Senior explanations show why a design was chosen under constraints.","Limitation: a limitation is a constraint; a tradeoff is an intentional balance between competing properties.","The tradeoff was slightly higher storage cost in exchange for durable replay evidence.",["choice","cost","benefit"]),
V("Acceptance criteria","Communication","Explicit conditions that define when a task or product is considered complete.","They turn ambiguous 'done' into testable outcomes.","Requirement: requirements describe needs; acceptance criteria define verifiable completion.","I turned 'fix the pipeline' into six acceptance criteria that had to pass before publication.",["done","condition","test"]),
V("Business impact","Communication","The measurable effect of technical work on revenue, cost, risk, customer experience, or operations.","It connects engineering decisions to why the organization should care.","Technical output: output says what was built; impact says what changed for the business.","The business impact was trusted inventory, fewer duplicate bookings, and faster recovery.",["business","effect","value"])
];

var stars=[
{title:"Reservation replay duplicates occupancy",world:"Ingestion Gateway",s:"A Kafka replay after consumer restart duplicated reservation events and pushed occupancy above source truth.",t:"Restore correct inventory without losing valid events and prevent retry from repeating the incident.",a:["Bound the affected offsets and business keys","Preserve raw captures","Deduplicate by stable reservation identity/version","Reconcile Gold against source","Add duplicate-rate alert and replay runbook"],r:"Restored one correct reservation contribution per business event and created repeat-safe recovery evidence.",why:"I used stable business identity instead of Kafka offset alone because the same logical event can arrive at a new physical offset.",metrics:["duplicate rate","reconciliation delta","freshness","MTTR"]},
{title:"Late inventory corrections",world:"Inventory Cove",s:"Late reservation changes arrived after daily inventory reporting and changed prior-day availability.",t:"Apply valid corrections while preserving historical auditability and deterministic current state.",a:["Declare inventory grain","Use event-time/effective intervals","Apply SCD2/Delta MERGE","Recompute affected partitions only","Reconcile totals before publish"],r:"Late corrections updated the intended historical/current state without rewriting unrelated inventory.",why:"I chose bounded SCD2/MERGE instead of full overwrite because we needed history plus controlled mutation scope.",metrics:["late-event count","affected partitions","reconciliation delta","scan reduction"]},
{title:"Customer 360 duplicates",world:"Customer Summit",s:"The same guest appeared under multiple profiles, causing household and segmentation counts to drift.",t:"Create a trusted customer identity without unsafe fuzzy merges.",a:["Use deterministic IDs first","Score fuzzy candidates second","Declare household grain","Add uniqueness/relationship tests","Publish conformed customer dimensions"],r:"Reduced duplicate customer identities while preserving ambiguous matches for review.",why:"I did not fuzzy-match everything because false merges are harder to repair than unresolved candidates.",metrics:["duplicate identity rate","match confidence","DQ failures","segment count delta"]},
{title:"Friday release regression",world:"Release Keep",s:"A production bundle increased error rate after release and configuration differed from staging.",t:"Restore service quickly and prevent environment drift.",a:["Freeze promotion","Rollback last-known-good bundle","Validate data state","Move config into versioned bundle targets","Gate future releases with tests"],r:"Recovered the prior stable release and made promotion reproducible across environments.",why:"Rollback reduced variables during incident response; patching forward would have changed the system before root cause was isolated.",metrics:["error rate","rollback RTO","failed gates","deployment lead time"]},
{title:"Training-serving skew",world:"Feature Forge",s:"Offline guest propensity validation was strong, but production scores diverged because online preprocessing differed.",t:"Restore parity and make shared features reusable.",a:["Compare offline/online samples","Identify default/window mismatch","Centralize feature definition","Add parity tests and freshness metadata","Backfill point-in-time-correct history"],r:"Production scoring aligned with offline behavior and feature logic became reusable across models.",why:"Shared feature contracts reduce independent implementations that silently drift.",metrics:["parity delta","feature freshness","prediction delta","test pass rate"]},
{title:"Holiday forecast leakage",world:"Forecast Terrace",s:"A demand model looked excellent offline because a holiday feature contained information unavailable at forecast time.",t:"Remove leakage and establish trustworthy forecasting evaluation.",a:["Define forecast creation time","Enforce feature availability","Use rolling backtests","Evaluate destination/lead-time slices","Add drift/error thresholds"],r:"Produced realistic forecast metrics that could support staffing decisions without future-data leakage.",why:"Time-respecting backtests match the production problem; random splits would overstate quality.",metrics:["MAPE","slice error","backtest stability","staffing impact"]},
{title:"AI concierge cites stale policy",world:"AI Knowledge Archive",s:"The concierge answered cancellation questions from an outdated policy document.",t:"Make generated answers current, grounded, and auditable.",a:["Version policy sources","Filter retrieval by effective dates","Require citations","Trace model/retrieval versions","Add unsupported-claim guardrail"],r:"Answers were tied to active approved policy evidence with reconstructable traces.",why:"RAG with governed retrieval was safer than relying on model memory for changing policy facts.",metrics:["citation coverage","retrieval precision","stale-source rate","guardrail blocks"]},
{title:"2 AM freshness SLO breach",world:"Incident Citadel",s:"Reservation freshness breached SLO while the pipeline dashboard still showed successful tasks.",t:"Find the real failure without destroying evidence and restore trusted business state.",a:["Scope blast radius","Preserve logs/checkpoints","Trace last change","Verify hypothesis","Recover bounded scope","Reconcile before close"],r:"Restored freshness and added an evidence-first incident path tied to business validation.",why:"A green task is local evidence only; end-to-end correctness required downstream reconciliation.",metrics:["SLO burn","freshness","MTTR","affected resorts"]},
{title:"Checkpoint recovery after stream failure",world:"Delta Harbor",s:"A damaged checkpoint blocked restart and deleting it risked replaying a large source range.",t:"Recover the stream without duplicate business effects.",a:["Find last proven frontier","Bound replay range","Verify sink idempotency","Use isolated recovery checkpoint","Reconcile counts before resume"],r:"Recovered processing from a proven boundary without unbounded replay.",why:"Checkpoint reset was only safe after external state and replay boundaries were independently proven.",metrics:["replay range","duplicate rate","checkpoint lag","recovery time"]},
{title:"Model champion slice regression",world:"MLflow Observatory",s:"A newly promoted model improved aggregate score but regressed a high-value destination slice.",t:"Protect production quality while preserving experiment lineage.",a:["Compare champion/challenger by slice","Rollback known-good model","Record failed gate","Add slice-aware promotion policy","Trigger retraining only with evidence"],r:"Restored prior production quality and strengthened model promotion controls.",why:"Aggregate improvement did not justify a critical slice regression; promotion needed business-relevant gates.",metrics:["slice metric","aggregate metric","rollback RTO","drift"]},
{title:"Campaign writeback divergence",world:"Enterprise Recovery",s:"A promotion export showed success while Snowflake authorization history, Segment, a legacy CRM, and feedback state disagreed.",t:"Restore one certified business state without duplicate writes or manufactured audit history.",a:["Prove source continuity","Reconstruct missing authorization history","Create stable destination operation IDs","Resolve uncertain outcomes by lookup","Fence overlapping workers","Reconcile both destinations","Publish with compare-and-swap"],r:"Produced a repeatable recovery model where retries could not create new business effects and incomplete evidence could not publish.",why:"No distributed transaction spanned all systems, so I used durable authorization, idempotent commands, reconciliation, and fail-closed publication.",metrics:["changed keys","new applications","history count","reconciliation mismatch","recovery time","credits"]},
{title:"Warehouse recovery scan explosion",world:"Enterprise Recovery",s:"The first recovery design scanned 1.8 TiB to repair a bounded incident population.",t:"Reduce cost and time without weakening correctness proof.",a:["Freeze input cut","Materialize affected keys","Prune source/target reads","Aggregate before joins","Inspect query profiles","Scale compute only after bounding work"],r:"Converted the recovery from full-history behavior to measurable bounded-scope execution.",why:"More compute would only make unnecessary I/O more expensive; pruning removes work entirely.",metrics:["bytes scanned","warehouse credits","pruning percent","spill","elapsed time"]}
];

function categories(){var c={};vocab.forEach(function(v){c[v.cat]=1;});return Object.keys(c).sort();}
function filteredTerms(){return st.category==="all"?vocab:vocab.filter(function(v){return v.cat===st.category;});}
function currentTerm(){var a=filteredTerms();if(!a.length)return vocab[0];st.index=((st.index%a.length)+a.length)%a.length;return a[st.index];}
function statFor(term){return st.termStats[term]||{right:0,wrong:0,natural:0};}
function mastery(){var known=0;vocab.forEach(function(v){var s=statFor(v.term);if(s.right>=2&&s.natural>=1)known++;});return {known:known,pct:Math.round(known/vocab.length*100)};}
function choicesFor(term,mode){
 var same=vocab.filter(function(v){return v.cat===term.cat&&v.term!==term.term;});
 var others=shuffle(same.length>=3?same:vocab.filter(function(v){return v.term!==term.term;})).slice(0,3);
 if(mode==="definition")return shuffle([{label:term.def,correct:true}].concat(others.map(function(v){return {label:v.def,correct:false};})));
 return shuffle([{label:term.term,correct:true}].concat(others.map(function(v){return {label:v.term,correct:false};})));
}
function naturalScore(term,text){
 var low=text.toLowerCase(),hits=term.keys.filter(function(k){return low.indexOf(k.toLowerCase())>=0;});
 var score=Math.round(hits.length/term.keys.length*55)+Math.min(20,Math.floor(text.length/45));
 if(low.indexOf(term.term.toLowerCase())>=0)score+=10;
 if(/because|so that|which means|therefore|instead of|rather than/.test(low))score+=10;
 if(/production|business|retry|replay|quality|risk|metric|state|data|model/.test(low))score+=5;
 return Math.min(100,score);
}
function updateTerm(term,right,natural){
 var s=statFor(term.term);if(right===true)s.right++;if(right===false)s.wrong++;if(natural)s.natural++;st.termStats[term.term]=s;save();
}
function coachHTML(){
 var m=mastery(),weak=vocab.filter(function(v){var s=statFor(v.term);return s.wrong>s.right||s.right===0;}).slice(0,8);
 return '<div class="coach-head"><span class="micro">SPEAKING COACH</span><h3>Natural production language</h3></div><div class="coach-body">'+
 '<div class="coach-card"><b>Vocabulary mastery</b><div class="coach-score '+(m.pct>=80?"good":m.pct>=50?"mid":"low")+'">'+m.pct+'%</div><div class="speak-meter"><i style="width:'+m.pct+'%"></i></div><p>'+m.known+' / '+vocab.length+' terms have both recognition and natural-use evidence.</p></div>'+
 '<div class="coach-card"><b>Weak-term rotation</b><div class="term-bank">'+(weak.length?weak.map(function(v){return '<span class="term-chip weak">'+v.term+'</span>';}).join(""):'<span class="term-chip known">No weak terms yet</span>')+'</div></div>'+
 '<div class="coach-card"><b>Natural-speaking rule</b><p>Do not define a term in isolation. Use this sequence: <strong>problem → term/pattern → why → alternative → proof → business effect.</strong></p></div>'+
 '<div class="coach-card"><b>Interview compression</b><p>If your answer sounds like documentation, shorten it. If it sounds like a buzzword list, add the failure it solves and the evidence that proves it.</p></div></div>';
}
function renderVocab(){
 var root=$("#speakingMain"),term=currentTerm(),arr=filteredTerms(),pos=st.index+1,mode=st.vocabMode;
 var body="";
 if(mode==="definition"||mode==="reverse"){
  var opts=choicesFor(term,mode);
  var q=mode==="definition"?"Which definition best matches “"+term.term+"”?":"Which term matches this definition?";
  var sub=mode==="reverse"?term.def:"Choose the production meaning, not the closest buzzword.";
  body='<div class="question-kicker">'+term.cat+' • '+mode.toUpperCase()+'</div><h3 class="exam-question">'+esc(q)+'</h3><div class="exam-sub">'+esc(sub)+'</div><div class="exam-options">'+opts.map(function(o,i){return '<button class="exam-option" data-opt="'+i+'" data-correct="'+o.correct+'"><span class="opt-letter">'+String.fromCharCode(65+i)+'</span><span>'+esc(o.label)+'</span></button>';}).join("")+'</div><div class="exam-actions"><button class="primary" id="submitVocab">Check answer</button><button id="nextVocab">Next term</button></div><div id="vocabFeedback"></div>';
 }else if(mode==="contrast"){
  body='<div class="question-kicker">'+term.cat+' • CONTRAST</div><h3 class="exam-question">Explain “'+esc(term.term)+'” versus the closest competing method.</h3><div class="exam-sub">Say what each one means, the decision boundary, and when you would use each.</div><textarea id="vocabText" class="exam-input" placeholder="Explain it naturally..."></textarea><div class="exam-actions"><button class="primary" id="gradeText">Grade contrast</button><button id="revealVocab">Reveal model answer</button><button id="nextVocab">Next</button></div><div id="vocabFeedback"></div>';
 }else if(mode==="natural"){
  body='<div class="question-kicker">'+term.cat+' • NATURAL SPEECH</div><h3 class="exam-question">Use “'+esc(term.term)+'” naturally while explaining a production project.</h3><div class="exam-sub">Do not give a textbook definition. Explain the problem it solved and why you used it.</div><textarea id="vocabText" class="exam-input" placeholder="Example: I used ... because ... instead of ..."></textarea><div class="exam-actions"><button class="primary" id="gradeText">Grade natural use</button><button id="voiceVocab">🎙 Voice answer</button><button id="revealVocab">Show natural example</button><button id="nextVocab">Next</button></div><div id="vocabFeedback"></div>';
 }else{
  body='<div class="question-kicker">'+term.cat+' • RAPID FIRE</div><h3 class="exam-question">'+esc(term.term)+'</h3><div class="exam-sub">You have one speaking turn: define it, say why it matters, contrast it, and use it in a project sentence.</div><textarea id="vocabText" class="exam-input short" placeholder="Speak or type your answer..."></textarea><div class="exam-actions"><button class="primary" id="gradeText">Score rapid answer</button><button id="voiceVocab">🎙 Voice answer</button><button id="nextVocab">Skip / next</button></div><div id="vocabFeedback"></div>';
 }
 root.innerHTML='<div class="exam-head"><div><span class="micro">"+vocab.length+"-TERM PRODUCTION VOCABULARY</span><h2>Vocabulary Exam</h2><p>Recognition is only step one. Mastery requires explaining why the term matters, contrasting it with a nearby concept, and using it naturally in a production sentence.</p></div><div class="exam-progress"><b>'+pos+' / '+arr.length+'</b><span>'+term.cat+'</span><div class="exam-track"><i style="width:'+Math.round(pos/arr.length*100)+'%"></i></div></div></div><div class="exam-body">'+body+'</div>';
 wireVocab(term,mode);
}
function wireVocab(term,mode){
 var selected=null;
 $$("[data-opt]",$("#speakingMain")).forEach(function(b){b.onclick=function(){$$("[data-opt]",$("#speakingMain")).forEach(function(x){x.classList.remove("selected");});b.classList.add("selected");selected=b;};});
 var submit=$("#submitVocab");if(submit)submit.onclick=function(){
  if(!selected){CO.toast("Choose an answer first");return;}st.attempts++;var right=selected.dataset.correct==="true";if(right)st.correct++;updateTerm(term,right,false);
  selected.classList.add(right?"correct":"wrong");if(!right){var good=$$("[data-correct=true]",$("#speakingMain"))[0];if(good)good.classList.add("correct");}
  $("#vocabFeedback").innerHTML=answerHTML(term,right?100:35);save();
 };
 var next=$("#nextVocab");if(next)next.onclick=nextTerm;
 var grade=$("#gradeText");if(grade)grade.onclick=function(){
  var text=$("#vocabText").value.trim();if(!text){CO.toast("Give your answer first");return;}var score=naturalScore(term,text);st.attempts++;if(score>=75)st.correct++;updateTerm(term,score>=75,true);$("#vocabFeedback").innerHTML=answerHTML(term,score);save();
 };
 var reveal=$("#revealVocab");if(reveal)reveal.onclick=function(){$("#vocabFeedback").innerHTML=answerHTML(term,null);};
 var voice=$("#voiceVocab");if(voice)voice.onclick=function(){startVoice($("#vocabText"),voice);};
}
function answerHTML(term,score){
 var s=score===null?"MODEL":score+"%";
 return '<div class="answer-panel"><h4>'+s+' • '+esc(term.term)+'</h4><p><b>Meaning:</b> '+esc(term.def)+'</p><p><b>Why it matters:</b> '+esc(term.why)+'</p><p class="contrast"><b>Versus:</b> '+esc(term.vs)+'</p><p class="natural"><b>Natural project language:</b> “'+esc(term.natural)+'”</p></div>';
}
function nextTerm(){var a=filteredTerms();st.index=(st.index+1)%a.length;st.selected=null;save();renderVocab();renderCoach();}
function starScenario(){return stars[st.starIndex%stars.length];}
function renderStar(){
 var root=$("#speakingMain"),s=starScenario(),saved=st.starAnswers[st.starIndex]||{S:"",T:"",A:"",R:"",WHY:""},sc=st.starScores[st.starIndex];
 root.innerHTML='<div class="exam-head"><div><span class="micro">PRODUCTION STAR EXAM • '+esc(s.world)+'</span><h2>'+esc(s.title)+'</h2><p>Build the story from production evidence. The exam separately scores situation clarity, ownership, actions, result, WHY/tradeoff, metrics, and natural delivery.</p></div><div class="exam-progress"><b>'+(st.starIndex+1)+' / '+stars.length+'</b><span>STAR SCENARIO</span><div class="exam-track"><i style="width:'+Math.round((st.starIndex+1)/stars.length*100)+'%"></i></div></div></div>'+
 '<div class="exam-body"><div class="answer-panel"><h4>SCENARIO</h4><p>'+esc(s.s)+'</p><p><b>Your objective:</b> '+esc(s.t)+'</p></div>'+
 '<div class="star-builder">'+starBox("S","Situation","Context + production problem. Do not spend half the answer here.",saved.S)+starBox("T","Task","Your responsibility, constraint, and definition of done.",saved.T)+starBox("A","Action","What YOU did in sequence, including technical choices.",saved.A)+starBox("R","Result","Measured or evidence-backed outcome.",saved.R)+'</div>'+
 '<div class="star-box" style="margin-top:8px"><label><span class="star-letter">W</span>WHY / TRADEOFF</label><textarea id="star-WHY" placeholder="Why this approach versus another method?">'+esc(saved.WHY)+'</textarea></div>'+
 '<div class="exam-actions"><button class="primary" id="gradeStar">Grade STAR answer</button><button id="voiceStar">🎙 Dictate full answer</button><button id="modelStar">Reveal model structure</button><button id="nextStar">Next scenario</button></div>'+
 '<div id="starResult">'+(sc?starScoreHTML(sc,s):"")+'</div></div>';
 $("#gradeStar").onclick=function(){gradeStar(s);};
 $("#modelStar").onclick=function(){$("#starResult").innerHTML=modelStarHTML(s);};
 $("#nextStar").onclick=function(){saveStar();st.starIndex=(st.starIndex+1)%stars.length;save();renderStar();renderCoach();};
 $("#voiceStar").onclick=function(){var target=$("#star-A");startVoice(target,$("#voiceStar"));};
}
function starBox(letter,title,hint,val){return '<div class="star-box"><label><span class="star-letter">'+letter+'</span>'+title+'</label><div class="exam-sub">'+hint+'</div><textarea id="star-'+letter+'" placeholder="'+title+'...">'+esc(val)+'</textarea></div>';}
function saveStar(){var x={};["S","T","A","R","WHY"].forEach(function(k){var e=$("#star-"+k);if(e)x[k]=e.value;});st.starAnswers[st.starIndex]=x;save();}
function gradeStar(s){
 saveStar();var a=st.starAnswers[st.starIndex],all=(a.S+" "+a.T+" "+a.A+" "+a.R+" "+a.WHY).toLowerCase();
 function has(text,regs){return regs.filter(function(r){return r.test(text.toLowerCase());}).length;}
 var scores={};
 scores.situation=Math.min(100,35+Math.min(40,a.S.length/3)+has(a.S,[/problem|incident|failure|diverg|risk|stale|duplicate/])*10);
 scores.task=Math.min(100,30+Math.min(45,a.T.length/3)+has(a.T,[/my|responsib|needed|objective|restore|prevent|ensure/])*12);
 var actionHits=s.a.filter(function(x){var words=x.toLowerCase().split(/\s+/).filter(function(w){return w.length>5;});return words.some(function(w){return a.A.toLowerCase().indexOf(w)>=0;});}).length;
 scores.action=Math.min(100,35+actionHits*8+Math.min(25,a.A.length/10));
 var metricHits=s.metrics.filter(function(m){return all.indexOf(m.split(" ")[0])>=0;}).length;
 scores.result=Math.min(100,30+metricHits*12+Math.min(35,a.R.length/5));
 scores.why=Math.min(100,25+(/because|instead of|rather than|tradeoff|why/.test(a.WHY.toLowerCase())?30:0)+Math.min(45,a.WHY.length/4));
 scores.evidence=Math.min(100,metricHits*18+(/reconcile|test|metric|evidence|slo|rate|time|cost|count/.test(all)?28:0));
 scores.natural=Math.min(100,35+(/i |i\'d|i used|i chose|we /.test(all)?20:0)+(/because|so that|which meant|that allowed/.test(all)?20:0)+Math.min(25,all.length/80));
 var overall=Math.round(Object.values(scores).reduce(function(x,y){return x+y;},0)/Object.keys(scores).length);
 var out={overall:overall,scores:scores,ts:Date.now()};st.starScores[st.starIndex]=out;save();$("#starResult").innerHTML=starScoreHTML(out,s);CO.toast("STAR scored "+overall+"%");
}
function starScoreHTML(sc,s){
 var labels={situation:"Situation",task:"Task",action:"Action",result:"Result",why:"WHY / tradeoff",evidence:"Metrics / evidence",natural:"Natural delivery"};
 return '<div class="answer-panel"><h4>STAR SCORE • '+sc.overall+'%</h4><div class="star-rubric">'+Object.keys(sc.scores).map(function(k){return '<div class="star-rubric-row"><span>'+labels[k]+'</span><div class="star-rubric-track"><i style="width:'+sc.scores[k]+'%"></i></div><b>'+Math.round(sc.scores[k])+'%</b></div>';}).join("")+'</div><div class="natural-speech"><b>Coach</b><p>'+(sc.overall>=85?"This is interview-ready. Compress it once more and keep the WHY plus one or two metrics.":sc.scores.action<75?"Your Action section needs more first-person sequence: what you inspected, changed, tested, and proved.":sc.scores.why<75?"Add the decision logic: why you chose this method and what was wrong with the tempting alternative.":"Add stronger measurable evidence and make the result business-facing.")+'</p></div></div>';
}
function modelStarHTML(s){
 return '<div class="answer-panel"><h4>MODEL STAR STRUCTURE</h4><p><b>S:</b> '+esc(s.s)+'</p><p><b>T:</b> '+esc(s.t)+'</p><p><b>A:</b> '+esc(s.a.join(" → "))+'</p><p><b>R:</b> '+esc(s.r)+' Evidence: '+esc(s.metrics.join(", "))+'.</p><p class="contrast"><b>WHY:</b> '+esc(s.why)+'</p><p class="natural"><b>Natural delivery:</b> “I first bounded the failure and defined what correct state meant. Then I used the production pattern that gave me deterministic recovery, proved the downstream state rather than trusting a green job, and added the test/runbook that prevents the same incident from coming back.”</p></div>';
}
function renderCoach(){var c=$("#speakingCoach");if(c)c.innerHTML=coachHTML();}
function renderSidebar(){
 var side=$("#speakingSide");if(!side)return;
 side.innerHTML='<div class="speak-mode-list"><button class="speak-mode '+(st.mode==="vocab"?"active":"")+'" data-speak-mode="vocab"><b>Vocabulary Exam</b><span>"+vocab.length+" production terms + natural use</span></button><button class="speak-mode '+(st.mode==="star"?"active":"")+'" data-speak-mode="star"><b>STAR Exam</b><span>Production stories + WHY + metrics</span></button></div>'+
 '<div class="speak-settings">'+(st.mode==="vocab"?'<span class="micro">VOCAB MODE</span><select id="vocabMode"><option value="definition">Definition → answer</option><option value="reverse">Definition → term</option><option value="contrast">Contrast two methods</option><option value="natural">Use it naturally</option><option value="rapid">Rapid fire</option></select><span class="micro">CATEGORY</span><select id="vocabCategory"><option value="all">All "+vocab.length+" terms</option>'+categories().map(function(c){return '<option value="'+c+'">'+c+'</option>';}).join("")+'</select><button id="randomTerm">Random term</button>':'<span class="micro">STAR PROJECT</span><select id="starScenario">'+stars.map(function(s,i){return '<option value="'+i+'">'+(i+1)+'. '+s.title+'</option>';}).join("")+'</select><button id="randomStar">Random scenario</button>')+'</div>';
 $$("[data-speak-mode]",side).forEach(function(b){b.onclick=function(){st.mode=b.dataset.speakMode;save();renderAll();};});
 if(st.mode==="vocab"){
  $("#vocabMode").value=st.vocabMode;$("#vocabCategory").value=st.category;
  $("#vocabMode").onchange=function(e){st.vocabMode=e.target.value;st.answered=false;save();renderVocab();};
  $("#vocabCategory").onchange=function(e){st.category=e.target.value;st.index=0;save();renderVocab();renderCoach();};
  $("#randomTerm").onclick=function(){var a=filteredTerms();st.index=Math.floor(Math.random()*a.length);save();renderVocab();};
 }else{
  $("#starScenario").value=String(st.starIndex);
  $("#starScenario").onchange=function(e){saveStar();st.starIndex=+e.target.value;save();renderStar();};
  $("#randomStar").onclick=function(){saveStar();st.starIndex=Math.floor(Math.random()*stars.length);save();renderStar();};
 }
}
function startVoice(target,button){
 var SR=window.SpeechRecognition||window.webkitSpeechRecognition;
 if(!SR){CO.toast("Browser speech recognition is unavailable here — type the answer instead.");return;}
 var r=new SR();r.lang="en-US";r.interimResults=true;r.continuous=false;var original=button.textContent;button.textContent="Listening...";
 r.onresult=function(e){var text="";for(var i=e.resultIndex;i<e.results.length;i++)text+=e.results[i][0].transcript+" ";target.value=(target.value+" "+text).trim();};
 r.onerror=function(){button.textContent=original;CO.toast("Voice recognition stopped");};
 r.onend=function(){button.textContent=original;};
 r.start();
}
function renderAll(){renderSidebar();if(st.mode==="vocab")renderVocab();else renderStar();renderCoach();}
function install(){
 var nav=$("#nav"),work=$("#workspace");if(!nav||!work)return;
 var b=document.createElement("button");b.className="nav-item";b.dataset.view="speaking";b.innerHTML="<span>ABC</span><b>Vocab + STAR</b><em>15</em>";
 b.onclick=function(){CO.setView("speaking");$("#pageTitle").textContent="Vocabulary + STAR Speaking Lab";renderAll();};nav.appendChild(b);
 var sec=document.createElement("section");sec.className="view";sec.id="view-speaking";sec.innerHTML='<div class="view-heading"><div><span class="micro">SPEAKING FLUENCY LAB</span><h2>Vocabulary + STAR Exam</h2><p>Turn production terminology into language you can use naturally with interviewers, engineers, and stakeholders.</p></div><span class="enterprise-badge">"+vocab.length+" TERMS • "+stars.length+" STAR SCENARIOS</span></div><div class="speaking-shell"><aside class="speaking-sidebar glass" id="speakingSide"></aside><section class="speaking-main glass" id="speakingMain"></section><aside class="speaking-coach glass" id="speakingCoach"></aside></div>';work.appendChild(sec);
 renderAll();
}
install();
})();